# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trainingInput:
  scaleTier: BASIC-GPU
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: loss
    maxTrials: 200
    maxParallelTrials: 10
    params:
      - parameterName: hp-lr0
        type: DOUBLE
        maxValue: 0.05
        minValue: 0.0005
        scaleType: UNIT_LOG_SCALE
      - parameterName: hp-lr2
        type: INTEGER
        minValue: 300
        maxValue: 3000
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: hp-dropout
        type: DOUBLE
        minValue: 0.1
        maxValue: 0.5
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: hp-filter-sizes
        type: CATEGORICAL
        categoricalValues: ['S', 'M', 'L']
      - parameterName: hp-conv1
        type: INTEGER
        minValue: 6
        maxValue: 16
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: hp-dense
        type: INTEGER
        minValue: 10
        maxValue: 200
        scaleType: UNIT_LINEAR_SCALE

# results
#"trialId": "71",
#  "hyperparameters": {
#    "hp-filter-sizes": "S",
#    "hp-conv1": "16",
#    "hp-dropout": "0.11030263313388372",
#    "hp-dense": "43",
#    "hp-lr0": "0.0086126130847661575",
#    "hp-lr2": "888"
#  },
#  "finalMetric": {
#    "trainingStep": "5000",
#    "objectiveValue": 2.62571907043
#  }
# final accuracy: 99.1%
# max accuracy: 99.18%

# "trialId": "156",
#  "hyperparameters": {
#    "hp-filter-sizes": "S",
#    "hp-conv1": "16",
#    "hp-dropout": "0.49902031905783584",
#    "hp-dense": "104",
#    "hp-lr0": "0.025623941309865606",
#    "hp-lr2": "683"
#  },
#  "finalMetric": {
#    "trainingStep": "5000",
#    "objectiveValue": 2.99048638344
#  }
# final accuracy: 99.18%
# max accuracy: 99.18%

#"trialId": "90",
#  "hyperparameters": {
#    "hp-filter-sizes": "S",
#    "hp-conv1": "15",
#    "hp-dropout": "0.49878404991126746",
#    "hp-dense": "120",
#    "hp-lr0": "0.0095452876595402188",
#    "hp-lr2": "1889"
#  },
#  "finalMetric": {
#    "trainingStep": "5000",
#    "objectiveValue": 3.01515436172
#  }
# final accuracy: 99.14%
# max accuracy: 99.14%
# lr too high, switched local min @2000 steps