description: ""
# YOLO v27
#deploymentUri:   gs://ml1-demo-martin/jobs/plane663/export/planesnet/1518717311/
# YOLO v26
#deploymentUri:   gs://ml1-demo-martin/jobs/plane664b/export/planesnet/1518737239/
# YOLO v25
# deploymentUri:   gs://ml1-demo-martin/jobs/plane657/export/planesnet/1518700222/
# YOLO v24
# deploymentUri:   gs://ml1-demo-martin/jobs/plane647/export/planesnet/1518722018/
# YOLO v23
# deploymentUri:   gs://ml1-demo-martin/jobs/plane533/export/planesnet/1518180119/
# YOLO v22
# deploymentUri:   gs://ml1-demo-martin/jobs/plane569/export/planesnet/1518224289/
# YOLO v21
# deploymentUri:   gs://ml1-demo-martin/jobs/plane578/export/planesnet/1518446174/
# YOLO v20
deploymentUri:   gs://ml1-demo-martin/jobs/plane536/export/planesnet/1518188266/
# YOLO v19
# deploymentUri:   gs://ml1-demo-martin/jobs/plane533/export/planesnet/1518180119/
# YOLO v18
# deploymentUri: gs://ml1-demo-martin/jobs/plane355/export/planesnet/1516993495
# YOLO v5
# deploymentUri: gs://ml1-demo-martin/jobs/plane222/export/Servo/1508828444/
# YOLO v1
# deploymentUri: gs://ml1-demo-martin/jobs/plane172/export/Servo/1507918389/
# 20x20 tile v7_256x256
# deploymentUri: gs://ml1-demo-martin/jobs/plane064/1/export/Servo/1508870182
# 20x20 tile v02
# deploymentUri: gs://ml1-demo-martin/jobs/plane234/export/Servo/1509145962
# 20x20 tile v00
#deploymentUri: gs://ml1-demo-martin/jobs/plane232/export/Servo/1509141478
runtimeVersion: '1.4'
#autoScaling:
#  minNodes: 10