description: "5 instaces min"
# YOLO v18
# deploymentUri: gs://ml1-demo-martin/jobs/plane355/export/planesnet/1516993495
# YOLO v5
# deploymentUri: gs://ml1-demo-martin/jobs/plane222/export/Servo/1508828444/
# YOLO v1
# deploymentUri: gs://ml1-demo-martin/jobs/plane172/export/Servo/1507918389/
# 20x20 tile v7_256x256
deploymentUri: gs://ml1-demo-martin/jobs/plane064/1/export/Servo/1508870182
# 20x20 tile v02
# deploymentUri: gs://ml1-demo-martin/jobs/plane234/export/Servo/1509145962
# 20x20 tile v00
#deploymentUri: gs://ml1-demo-martin/jobs/plane232/export/Servo/1509141478

runtimeVersion: '1.4'
autoScaling:
  minNodes: 10