# To use this:
# gcloud ml-engine versions create v7 \
# --model plane_jpeg_scan_100_200_300_400_600_900_logged2 \
# --origin gs://ml1-demo-martin/jobs/plane064/1/export/Servo/1506462261/ \
# --runtime-version 1.2 --config predictions_deploy_config.yaml

runtimeVersion: '1.2'
#manualScaling:
#  nodes: 10  # The number of nodes to allocate for this model.
autoScaling:
  minNodes: 10  # The minimum number of nodes to allocate for this model.